---
services:
  weaviate:
    command:
    - --host
    - 0.0.0.0
    - --port
    - '8080'
    - --scheme
    - http
    - --write-timeout=600s
    - --read-timeout=600s
    image: cr.weaviate.io/semitechnologies/weaviate:1.34.5
    ports:
    - 8080:8080
    - 50051:50051
    volumes:
    - ./.data/weaviate:/var/lib/weaviate
    restart: on-failure:0
    environment:
      QUERY_DEFAULTS_LIMIT: 25
      AUTHENTICATION_ANONYMOUS_ACCESS_ENABLED: 'true'
      PERSISTENCE_DATA_PATH: '/var/lib/weaviate'
      CLUSTER_HOSTNAME: 'weaviate-0'
      DEFAULT_VECTORIZER_MODULE: 'none'
      MODULES_CLIENT_TIMEOUT: '600s'
      ENABLE_MODULES: 'multi2vec-clip'
      CLIP_INFERENCE_API: 'http://m2v-clip-facebook-metaclip-2-worldwide-b32-384:8080'
  m2v-clip-facebook-metaclip-2-worldwide-b32-384:
    image: cr.weaviate.io/semitechnologies/multi2vec-clip:facebook-metaclip-2-worldwide-b32-384
    environment:
      ENABLE_CUDA: '0'
  m2v-clip-ModernVBERT-modernvbert-embed:
    image: cr.weaviate.io/semitechnologies/multi2vec-clip:ModernVBERT-modernvbert-embed
    environment:
      ENABLE_CUDA: '0'
  m2v-clip-xlm-roberta-base-ViT-B-32-laion5b_s13b_b90k:
    image: cr.weaviate.io/semitechnologies/multi2vec-clip:xlm-roberta-base-ViT-B-32-laion5b_s13b_b90k
    environment:
      ENABLE_CUDA: '0'
  m2v-clip-google-siglip2-so400m-patch16-384:
    image: cr.weaviate.io/semitechnologies/multi2vec-clip:google-siglip2-so400m-patch16-384
    environment:
      ENABLE_CUDA: '0'
...